# Generated by Django 5.1.6 on 2026-07-04 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course_level_course_status_course_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('review', models.TextField(blank=True, verbose_name='ulasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='mata kuliah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'Review Course',
                'verbose_name_plural': 'Review Course',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='courses.course', verbose_name='mata kuliah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_wishlists', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'Wishlist Course',
                'verbose_name_plural': 'Wishlist Course',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
