# Generated by Django 5.1.6 on 2026-07-04 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursereview_coursewishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='pengajar'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contents', to='courses.course', verbose_name='matkul'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='courses.course', verbose_name='matkul'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_memberships', to=settings.AUTH_USER_MODEL, verbose_name='siswa'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course_id', 'user_id')},
        ),
    ]
