# Generated by Django 5.1.6 on 2026-07-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_teacher_alter_coursecontent_course_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['course_id', 'order', 'id'], 'verbose_name': 'Konten Kelas', 'verbose_name_plural': 'Konten Kelas'},
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='urutan'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='courses/materials/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='courses.coursecontent', verbose_name='induk'),
        ),
    ]
