# Generated by Django 5.1.6 on 2026-07-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursecontent_options_coursecontent_order_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['lesson__order', 'lesson__id']},
        ),
        migrations.AlterField(
            model_name='progress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.coursecontent'),
        ),
    ]
